version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - lll
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gocritic
    - revive

  settings:
    lll:
      line-length: 100
      tab-width: 4
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: blank-imports
          disabled: true
        - name: unexported-return
          disabled: true
        - name: var-naming

  exclusions:
    rules:
      - path: "docs/"
        linters:
          - lll
          - gocritic
          - revive
          - staticcheck
      - path: "mocks\\.go"
        linters:
          - lll
          - gocritic
          - revive
      - path: "config\\.go"
        linters:
          - lll
      - source: "^//go:generate "
        linters:
          - lll

formatters:
  enable:
    - gofumpt

run:
  timeout: 5m
