// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/service/deal (interfaces: DealRepository,ChannelRepository,PostRepository,UserRepository,Transactor)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=deal . DealRepository,ChannelRepository,PostRepository,UserRepository,Transactor
//

// Package deal is a generated GoMock package.
package deal

import (
	context "context"
	reflect "reflect"

	entity "github.com/bpva/ad-marketplace/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDealRepository is a mock of DealRepository interface.
type MockDealRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDealRepositoryMockRecorder
	isgomock struct{}
}

// MockDealRepositoryMockRecorder is the mock recorder for MockDealRepository.
type MockDealRepositoryMockRecorder struct {
	mock *MockDealRepository
}

// NewMockDealRepository creates a new mock instance.
func NewMockDealRepository(ctrl *gomock.Controller) *MockDealRepository {
	mock := &MockDealRepository{ctrl: ctrl}
	mock.recorder = &MockDealRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDealRepository) EXPECT() *MockDealRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDealRepository) Create(ctx context.Context, deal *entity.Deal) (*entity.Deal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, deal)
	ret0, _ := ret[0].(*entity.Deal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDealRepositoryMockRecorder) Create(ctx, deal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDealRepository)(nil).Create), ctx, deal)
}

// GetByAdvertiserID mocks base method.
func (m *MockDealRepository) GetByAdvertiserID(ctx context.Context, advertiserID uuid.UUID, limit, offset int) ([]entity.Deal, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAdvertiserID", ctx, advertiserID, limit, offset)
	ret0, _ := ret[0].([]entity.Deal)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAdvertiserID indicates an expected call of GetByAdvertiserID.
func (mr *MockDealRepositoryMockRecorder) GetByAdvertiserID(ctx, advertiserID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAdvertiserID", reflect.TypeOf((*MockDealRepository)(nil).GetByAdvertiserID), ctx, advertiserID, limit, offset)
}

// GetByChannelID mocks base method.
func (m *MockDealRepository) GetByChannelID(ctx context.Context, channelID uuid.UUID, limit, offset int) ([]entity.Deal, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChannelID", ctx, channelID, limit, offset)
	ret0, _ := ret[0].([]entity.Deal)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByChannelID indicates an expected call of GetByChannelID.
func (mr *MockDealRepositoryMockRecorder) GetByChannelID(ctx, channelID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChannelID", reflect.TypeOf((*MockDealRepository)(nil).GetByChannelID), ctx, channelID, limit, offset)
}

// GetByID mocks base method.
func (m *MockDealRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Deal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Deal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDealRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDealRepository)(nil).GetByID), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockDealRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status entity.DealStatus, note *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDealRepositoryMockRecorder) UpdateStatus(ctx, id, status, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDealRepository)(nil).UpdateStatus), ctx, id, status, note)
}

// MockChannelRepository is a mock of ChannelRepository interface.
type MockChannelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChannelRepositoryMockRecorder
	isgomock struct{}
}

// MockChannelRepositoryMockRecorder is the mock recorder for MockChannelRepository.
type MockChannelRepositoryMockRecorder struct {
	mock *MockChannelRepository
}

// NewMockChannelRepository creates a new mock instance.
func NewMockChannelRepository(ctrl *gomock.Controller) *MockChannelRepository {
	mock := &MockChannelRepository{ctrl: ctrl}
	mock.recorder = &MockChannelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelRepository) EXPECT() *MockChannelRepositoryMockRecorder {
	return m.recorder
}

// GetAdFormatsByChannelID mocks base method.
func (m *MockChannelRepository) GetAdFormatsByChannelID(ctx context.Context, channelID uuid.UUID) ([]entity.ChannelAdFormat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdFormatsByChannelID", ctx, channelID)
	ret0, _ := ret[0].([]entity.ChannelAdFormat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdFormatsByChannelID indicates an expected call of GetAdFormatsByChannelID.
func (mr *MockChannelRepositoryMockRecorder) GetAdFormatsByChannelID(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdFormatsByChannelID", reflect.TypeOf((*MockChannelRepository)(nil).GetAdFormatsByChannelID), ctx, channelID)
}

// GetByID mocks base method.
func (m *MockChannelRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockChannelRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockChannelRepository)(nil).GetByID), ctx, id)
}

// GetByTgChannelID mocks base method.
func (m *MockChannelRepository) GetByTgChannelID(ctx context.Context, tgChannelID int64) (*entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgChannelID", ctx, tgChannelID)
	ret0, _ := ret[0].(*entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgChannelID indicates an expected call of GetByTgChannelID.
func (mr *MockChannelRepositoryMockRecorder) GetByTgChannelID(ctx, tgChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgChannelID", reflect.TypeOf((*MockChannelRepository)(nil).GetByTgChannelID), ctx, tgChannelID)
}

// GetOwnerWalletAddress mocks base method.
func (m *MockChannelRepository) GetOwnerWalletAddress(ctx context.Context, channelID uuid.UUID) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerWalletAddress", ctx, channelID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerWalletAddress indicates an expected call of GetOwnerWalletAddress.
func (mr *MockChannelRepositoryMockRecorder) GetOwnerWalletAddress(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerWalletAddress", reflect.TypeOf((*MockChannelRepository)(nil).GetOwnerWalletAddress), ctx, channelID)
}

// GetRole mocks base method.
func (m *MockChannelRepository) GetRole(ctx context.Context, channelID, userID uuid.UUID) (*entity.ChannelRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, channelID, userID)
	ret0, _ := ret[0].(*entity.ChannelRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockChannelRepositoryMockRecorder) GetRole(ctx, channelID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockChannelRepository)(nil).GetRole), ctx, channelID, userID)
}

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
	isgomock struct{}
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// AddAdVersion mocks base method.
func (m *MockPostRepository) AddAdVersion(ctx context.Context, dealID uuid.UUID, version int, posts []entity.Post) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdVersion", ctx, dealID, version, posts)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAdVersion indicates an expected call of AddAdVersion.
func (mr *MockPostRepositoryMockRecorder) AddAdVersion(ctx, dealID, version, posts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdVersion", reflect.TypeOf((*MockPostRepository)(nil).AddAdVersion), ctx, dealID, version, posts)
}

// CopyAsAd mocks base method.
func (m *MockPostRepository) CopyAsAd(ctx context.Context, templatePostID, dealID uuid.UUID, version int) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyAsAd", ctx, templatePostID, dealID, version)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyAsAd indicates an expected call of CopyAsAd.
func (mr *MockPostRepositoryMockRecorder) CopyAsAd(ctx, templatePostID, dealID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyAsAd", reflect.TypeOf((*MockPostRepository)(nil).CopyAsAd), ctx, templatePostID, dealID, version)
}

// GetByID mocks base method.
func (m *MockPostRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostRepository)(nil).GetByID), ctx, id)
}

// GetLatestAd mocks base method.
func (m *MockPostRepository) GetLatestAd(ctx context.Context, dealID uuid.UUID) ([]entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAd", ctx, dealID)
	ret0, _ := ret[0].([]entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAd indicates an expected call of GetLatestAd.
func (mr *MockPostRepositoryMockRecorder) GetLatestAd(ctx, dealID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAd", reflect.TypeOf((*MockPostRepository)(nil).GetLatestAd), ctx, dealID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTransactor) WithTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactorMockRecorder) WithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactor)(nil).WithTx), ctx, f)
}
