// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/service/stats (interfaces: MTProtoClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=stats . MTProtoClient
//

// Package stats is a generated GoMock package.
package stats

import (
	context "context"
	reflect "reflect"

	dto "github.com/bpva/ad-marketplace/internal/dto"
	entity "github.com/bpva/ad-marketplace/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMTProtoClient is a mock of MTProtoClient interface.
type MockMTProtoClient struct {
	ctrl     *gomock.Controller
	recorder *MockMTProtoClientMockRecorder
	isgomock struct{}
}

// MockMTProtoClientMockRecorder is the mock recorder for MockMTProtoClient.
type MockMTProtoClientMockRecorder struct {
	mock *MockMTProtoClient
}

// NewMockMTProtoClient creates a new mock instance.
func NewMockMTProtoClient(ctrl *gomock.Controller) *MockMTProtoClient {
	mock := &MockMTProtoClient{ctrl: ctrl}
	mock.recorder = &MockMTProtoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMTProtoClient) EXPECT() *MockMTProtoClientMockRecorder {
	return m.recorder
}

// GetBroadcastStats mocks base method.
func (m *MockMTProtoClient) GetBroadcastStats(ctx context.Context, channelID int64, statsDC int) (*entity.BroadcastStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcastStats", ctx, channelID, statsDC)
	ret0, _ := ret[0].(*entity.BroadcastStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBroadcastStats indicates an expected call of GetBroadcastStats.
func (mr *MockMTProtoClientMockRecorder) GetBroadcastStats(ctx, channelID, statsDC any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcastStats", reflect.TypeOf((*MockMTProtoClient)(nil).GetBroadcastStats), ctx, channelID, statsDC)
}

// GetChannelFull mocks base method.
func (m *MockMTProtoClient) GetChannelFull(ctx context.Context, channelID int64) (*dto.ChannelFullInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelFull", ctx, channelID)
	ret0, _ := ret[0].(*dto.ChannelFullInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelFull indicates an expected call of GetChannelFull.
func (mr *MockMTProtoClientMockRecorder) GetChannelFull(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelFull", reflect.TypeOf((*MockMTProtoClient)(nil).GetChannelFull), ctx, channelID)
}
