/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Telegram init data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List user channels */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ChannelsResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get channel */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ChannelResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}/ad-formats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get channel ad formats */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AdFormatsResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /** Add channel ad format */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      /** @description Ad format details */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddAdFormatRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}/ad-formats/{formatID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove channel ad format */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
          /** @description Ad format UUID */
          formatID: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}/admins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get channel admins */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ChannelAdminsResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}/listing": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update channel listing */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      /** @description Listing status */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateListingRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    trace?: never;
  };
  "/channels/{TgChannelID}/managers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get channel managers */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ChannelManagersResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /** Add channel manager */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
        };
        cookie?: never;
      };
      /** @description Manager telegram ID */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddManagerRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{TgChannelID}/managers/{tgID}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove channel manager */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Telegram channel ID */
          TgChannelID: number;
          /** @description Manager telegram ID */
          tgID: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user name */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description New name */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateNameRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    trace?: never;
  };
  "/user/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProfileResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user settings */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Settings to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateSettingsRequest"];
        };
      };
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "*/*": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdFormatResponse: {
      feed_hours?: number;
      format_type?: components["schemas"]["AdFormatType"];
      id?: string;
      is_native?: boolean;
      price_nano_ton?: number;
      top_hours?: number;
    };
    /** @enum {string} */
    AdFormatType: "post" | "repost" | "story";
    AdFormatsResponse: {
      ad_formats?: components["schemas"]["AdFormatResponse"][];
    };
    AddAdFormatRequest: {
      feed_hours: number;
      format_type: components["schemas"]["AdFormatType"];
      is_native?: boolean;
      price_nano_ton: number;
      top_hours: number;
    };
    AddManagerRequest: {
      telegram_id: number;
    };
    AuthRequest: {
      init_data?: string;
    };
    AuthResponse: {
      token?: string;
      user?: components["schemas"]["UserResponse"];
    };
    ChannelAdmin: {
      first_name?: string;
      last_name?: string;
      telegram_id?: number;
      username?: string;
    };
    ChannelAdminsResponse: {
      admins?: components["schemas"]["ChannelAdmin"][];
    };
    ChannelManagersResponse: {
      managers?: components["schemas"]["ManagerResponse"][];
    };
    ChannelResponse: {
      id?: number;
      is_listed?: boolean;
      title?: string;
      username?: string;
    };
    /** @enum {string} */
    ChannelRoleType: "undefined" | "owner" | "manager";
    ChannelWithRoleResponse: {
      channel?: components["schemas"]["ChannelResponse"];
      role?: components["schemas"]["ChannelRoleType"];
    };
    ChannelsResponse: {
      channels?: components["schemas"]["ChannelWithRoleResponse"][];
    };
    ErrorResponse: {
      details?: {
        [key: string]: unknown;
      };
      error_code?: string;
    };
    /** @enum {string} */
    Language: "en" | "ru";
    ManagerResponse: {
      created_at?: string;
      name?: string;
      role?: components["schemas"]["ChannelRoleType"];
      telegram_id?: number;
    };
    /** @enum {string} */
    PreferredMode: "publisher" | "advertiser";
    ProfileResponse: {
      language?: components["schemas"]["Language"];
      name?: string;
      onboarding_finished?: boolean;
      preferred_mode?: components["schemas"]["PreferredMode"];
      receive_notifications?: boolean;
      telegram_id?: number;
      theme?: components["schemas"]["Theme"];
    };
    /** @enum {string} */
    Theme: "light" | "dark" | "auto";
    UpdateListingRequest: {
      is_listed?: boolean;
    };
    UpdateNameRequest: {
      name: string;
    };
    UpdateSettingsRequest: {
      language?: components["schemas"]["Language"];
      onboarding_finished?: boolean;
      preferred_mode?: components["schemas"]["PreferredMode"];
      receive_notifications?: boolean;
      theme?: components["schemas"]["Theme"];
    };
    UserResponse: {
      name?: string;
      telegram_id?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
