// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/service/bot (interfaces: TelebotClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=bot . TelebotClient
//

// Package bot is a generated GoMock package.
package bot

import (
	reflect "reflect"

	dto "github.com/bpva/ad-marketplace/internal/dto"
	gomock "go.uber.org/mock/gomock"
	telebot "gopkg.in/telebot.v4"
)

// MockTelebotClient is a mock of TelebotClient interface.
type MockTelebotClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelebotClientMockRecorder
	isgomock struct{}
}

// MockTelebotClientMockRecorder is the mock recorder for MockTelebotClient.
type MockTelebotClientMockRecorder struct {
	mock *MockTelebotClient
}

// NewMockTelebotClient creates a new mock instance.
func NewMockTelebotClient(ctrl *gomock.Controller) *MockTelebotClient {
	mock := &MockTelebotClient{ctrl: ctrl}
	mock.recorder = &MockTelebotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelebotClient) EXPECT() *MockTelebotClientMockRecorder {
	return m.recorder
}

// AdminsOf mocks base method.
func (m *MockTelebotClient) AdminsOf(channelID int64) ([]dto.ChannelAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminsOf", channelID)
	ret0, _ := ret[0].([]dto.ChannelAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminsOf indicates an expected call of AdminsOf.
func (mr *MockTelebotClientMockRecorder) AdminsOf(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminsOf", reflect.TypeOf((*MockTelebotClient)(nil).AdminsOf), channelID)
}

// DownloadFile mocks base method.
func (m *MockTelebotClient) DownloadFile(fileID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", fileID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockTelebotClientMockRecorder) DownloadFile(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockTelebotClient)(nil).DownloadFile), fileID)
}

// GetChatPhoto mocks base method.
func (m *MockTelebotClient) GetChatPhoto(chatID int64) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatPhoto", chatID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChatPhoto indicates an expected call of GetChatPhoto.
func (mr *MockTelebotClientMockRecorder) GetChatPhoto(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatPhoto", reflect.TypeOf((*MockTelebotClient)(nil).GetChatPhoto), chatID)
}

// Handle mocks base method.
func (m *MockTelebotClient) Handle(endpoint any, h telebot.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", endpoint, h)
}

// Handle indicates an expected call of Handle.
func (mr *MockTelebotClientMockRecorder) Handle(endpoint, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockTelebotClient)(nil).Handle), endpoint, h)
}

// ProcessUpdate mocks base method.
func (m *MockTelebotClient) ProcessUpdate(upd telebot.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessUpdate", upd)
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockTelebotClientMockRecorder) ProcessUpdate(upd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockTelebotClient)(nil).ProcessUpdate), upd)
}

// Send mocks base method.
func (m *MockTelebotClient) Send(to telebot.Recipient, what any, opts ...any) (*telebot.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{to, what}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(*telebot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTelebotClientMockRecorder) Send(to, what any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, what}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTelebotClient)(nil).Send), varargs...)
}

// SendAlbum mocks base method.
func (m *MockTelebotClient) SendAlbum(to telebot.Recipient, a telebot.Album, opts ...any) ([]telebot.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{to, a}
	for _, a_2 := range opts {
		varargs = append(varargs, a_2)
	}
	ret := m.ctrl.Call(m, "SendAlbum", varargs...)
	ret0, _ := ret[0].([]telebot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlbum indicates an expected call of SendAlbum.
func (mr *MockTelebotClientMockRecorder) SendAlbum(to, a any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, a}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlbum", reflect.TypeOf((*MockTelebotClient)(nil).SendAlbum), varargs...)
}

// Token mocks base method.
func (m *MockTelebotClient) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockTelebotClientMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockTelebotClient)(nil).Token))
}
