// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/service/bot (interfaces: TelebotClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=bot_service . TelebotClient
//

// Package bot_service is a generated GoMock package.
package bot_service

import (
	reflect "reflect"

	dto "github.com/bpva/ad-marketplace/internal/dto"
	gomock "go.uber.org/mock/gomock"
	telebot "gopkg.in/telebot.v4"
)

// MockTelebotClient is a mock of TelebotClient interface.
type MockTelebotClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelebotClientMockRecorder
	isgomock struct{}
}

// MockTelebotClientMockRecorder is the mock recorder for MockTelebotClient.
type MockTelebotClientMockRecorder struct {
	mock *MockTelebotClient
}

// NewMockTelebotClient creates a new mock instance.
func NewMockTelebotClient(ctrl *gomock.Controller) *MockTelebotClient {
	mock := &MockTelebotClient{ctrl: ctrl}
	mock.recorder = &MockTelebotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelebotClient) EXPECT() *MockTelebotClientMockRecorder {
	return m.recorder
}

// AdminsOf mocks base method.
func (m *MockTelebotClient) AdminsOf(channelID int64) ([]dto.ChannelAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminsOf", channelID)
	ret0, _ := ret[0].([]dto.ChannelAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminsOf indicates an expected call of AdminsOf.
func (mr *MockTelebotClientMockRecorder) AdminsOf(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminsOf", reflect.TypeOf((*MockTelebotClient)(nil).AdminsOf), channelID)
}

// Handle mocks base method.
func (m *MockTelebotClient) Handle(endpoint any, h telebot.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", endpoint, h)
}

// Handle indicates an expected call of Handle.
func (mr *MockTelebotClientMockRecorder) Handle(endpoint, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockTelebotClient)(nil).Handle), endpoint, h)
}

// ProcessUpdate mocks base method.
func (m *MockTelebotClient) ProcessUpdate(upd telebot.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessUpdate", upd)
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockTelebotClientMockRecorder) ProcessUpdate(upd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockTelebotClient)(nil).ProcessUpdate), upd)
}

// Token mocks base method.
func (m *MockTelebotClient) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockTelebotClientMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockTelebotClient)(nil).Token))
}
