// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/http/app (interfaces: BotService,ChannelService,UserService)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=app . BotService,ChannelService,UserService
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	dto "github.com/bpva/ad-marketplace/internal/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBotService is a mock of BotService interface.
type MockBotService struct {
	ctrl     *gomock.Controller
	recorder *MockBotServiceMockRecorder
	isgomock struct{}
}

// MockBotServiceMockRecorder is the mock recorder for MockBotService.
type MockBotServiceMockRecorder struct {
	mock *MockBotService
}

// NewMockBotService creates a new mock instance.
func NewMockBotService(ctrl *gomock.Controller) *MockBotService {
	mock := &MockBotService{ctrl: ctrl}
	mock.recorder = &MockBotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotService) EXPECT() *MockBotServiceMockRecorder {
	return m.recorder
}

// ProcessUpdate mocks base method.
func (m *MockBotService) ProcessUpdate(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUpdate", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockBotServiceMockRecorder) ProcessUpdate(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockBotService)(nil).ProcessUpdate), data)
}

// Token mocks base method.
func (m *MockBotService) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockBotServiceMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockBotService)(nil).Token))
}

// MockChannelService is a mock of ChannelService interface.
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
	isgomock struct{}
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService.
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance.
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// AddAdFormat mocks base method.
func (m *MockChannelService) AddAdFormat(ctx context.Context, TgChannelID int64, req dto.AddAdFormatRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdFormat", ctx, TgChannelID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAdFormat indicates an expected call of AddAdFormat.
func (mr *MockChannelServiceMockRecorder) AddAdFormat(ctx, TgChannelID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdFormat", reflect.TypeOf((*MockChannelService)(nil).AddAdFormat), ctx, TgChannelID, req)
}

// AddManager mocks base method.
func (m *MockChannelService) AddManager(ctx context.Context, TgChannelID, tgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddManager", ctx, TgChannelID, tgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddManager indicates an expected call of AddManager.
func (mr *MockChannelServiceMockRecorder) AddManager(ctx, TgChannelID, tgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddManager", reflect.TypeOf((*MockChannelService)(nil).AddManager), ctx, TgChannelID, tgID)
}

// GetAdFormats mocks base method.
func (m *MockChannelService) GetAdFormats(ctx context.Context, TgChannelID int64) (*dto.AdFormatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdFormats", ctx, TgChannelID)
	ret0, _ := ret[0].(*dto.AdFormatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdFormats indicates an expected call of GetAdFormats.
func (mr *MockChannelServiceMockRecorder) GetAdFormats(ctx, TgChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdFormats", reflect.TypeOf((*MockChannelService)(nil).GetAdFormats), ctx, TgChannelID)
}

// GetChannel mocks base method.
func (m *MockChannelService) GetChannel(ctx context.Context, TgChannelID int64) (*dto.ChannelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, TgChannelID)
	ret0, _ := ret[0].(*dto.ChannelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockChannelServiceMockRecorder) GetChannel(ctx, TgChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockChannelService)(nil).GetChannel), ctx, TgChannelID)
}

// GetChannelAdmins mocks base method.
func (m *MockChannelService) GetChannelAdmins(ctx context.Context, TgChannelID int64) (*dto.ChannelAdminsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelAdmins", ctx, TgChannelID)
	ret0, _ := ret[0].(*dto.ChannelAdminsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelAdmins indicates an expected call of GetChannelAdmins.
func (mr *MockChannelServiceMockRecorder) GetChannelAdmins(ctx, TgChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelAdmins", reflect.TypeOf((*MockChannelService)(nil).GetChannelAdmins), ctx, TgChannelID)
}

// GetChannelManagers mocks base method.
func (m *MockChannelService) GetChannelManagers(ctx context.Context, TgChannelID int64) (*dto.ChannelManagersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelManagers", ctx, TgChannelID)
	ret0, _ := ret[0].(*dto.ChannelManagersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelManagers indicates an expected call of GetChannelManagers.
func (mr *MockChannelServiceMockRecorder) GetChannelManagers(ctx, TgChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelManagers", reflect.TypeOf((*MockChannelService)(nil).GetChannelManagers), ctx, TgChannelID)
}

// GetUserChannels mocks base method.
func (m *MockChannelService) GetUserChannels(ctx context.Context) (*dto.ChannelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChannels", ctx)
	ret0, _ := ret[0].(*dto.ChannelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChannels indicates an expected call of GetUserChannels.
func (mr *MockChannelServiceMockRecorder) GetUserChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChannels", reflect.TypeOf((*MockChannelService)(nil).GetUserChannels), ctx)
}

// RemoveAdFormat mocks base method.
func (m *MockChannelService) RemoveAdFormat(ctx context.Context, TgChannelID int64, formatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAdFormat", ctx, TgChannelID, formatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAdFormat indicates an expected call of RemoveAdFormat.
func (mr *MockChannelServiceMockRecorder) RemoveAdFormat(ctx, TgChannelID, formatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAdFormat", reflect.TypeOf((*MockChannelService)(nil).RemoveAdFormat), ctx, TgChannelID, formatID)
}

// RemoveManager mocks base method.
func (m *MockChannelService) RemoveManager(ctx context.Context, TgChannelID, tgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveManager", ctx, TgChannelID, tgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveManager indicates an expected call of RemoveManager.
func (mr *MockChannelServiceMockRecorder) RemoveManager(ctx, TgChannelID, tgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveManager", reflect.TypeOf((*MockChannelService)(nil).RemoveManager), ctx, TgChannelID, tgID)
}

// UpdateListing mocks base method.
func (m *MockChannelService) UpdateListing(ctx context.Context, TgChannelID int64, isListed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateListing", ctx, TgChannelID, isListed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateListing indicates an expected call of UpdateListing.
func (mr *MockChannelServiceMockRecorder) UpdateListing(ctx, TgChannelID, isListed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateListing", reflect.TypeOf((*MockChannelService)(nil).UpdateListing), ctx, TgChannelID, isListed)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockUserService) GetProfile(ctx context.Context) (*dto.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx)
	ret0, _ := ret[0].(*dto.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserServiceMockRecorder) GetProfile(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserService)(nil).GetProfile), ctx)
}

// UpdateName mocks base method.
func (m *MockUserService) UpdateName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockUserServiceMockRecorder) UpdateName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockUserService)(nil).UpdateName), ctx, name)
}

// UpdateSettings mocks base method.
func (m *MockUserService) UpdateSettings(ctx context.Context, req dto.UpdateSettingsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockUserServiceMockRecorder) UpdateSettings(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockUserService)(nil).UpdateSettings), ctx, req)
}
