// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/http/app (interfaces: ChannelService)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=app . ChannelService
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	dto "github.com/bpva/ad-marketplace/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelService is a mock of ChannelService interface.
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
	isgomock struct{}
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService.
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance.
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// AddManager mocks base method.
func (m *MockChannelService) AddManager(ctx context.Context, telegramChannelID, telegramID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddManager", ctx, telegramChannelID, telegramID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddManager indicates an expected call of AddManager.
func (mr *MockChannelServiceMockRecorder) AddManager(ctx, telegramChannelID, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddManager", reflect.TypeOf((*MockChannelService)(nil).AddManager), ctx, telegramChannelID, telegramID)
}

// GetChannel mocks base method.
func (m *MockChannelService) GetChannel(ctx context.Context, telegramChannelID int64) (*dto.ChannelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, telegramChannelID)
	ret0, _ := ret[0].(*dto.ChannelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockChannelServiceMockRecorder) GetChannel(ctx, telegramChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockChannelService)(nil).GetChannel), ctx, telegramChannelID)
}

// GetChannelAdmins mocks base method.
func (m *MockChannelService) GetChannelAdmins(ctx context.Context, telegramChannelID int64) ([]dto.ChannelAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelAdmins", ctx, telegramChannelID)
	ret0, _ := ret[0].([]dto.ChannelAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelAdmins indicates an expected call of GetChannelAdmins.
func (mr *MockChannelServiceMockRecorder) GetChannelAdmins(ctx, telegramChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelAdmins", reflect.TypeOf((*MockChannelService)(nil).GetChannelAdmins), ctx, telegramChannelID)
}

// GetChannelManagers mocks base method.
func (m *MockChannelService) GetChannelManagers(ctx context.Context, telegramChannelID int64) ([]dto.ManagerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelManagers", ctx, telegramChannelID)
	ret0, _ := ret[0].([]dto.ManagerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelManagers indicates an expected call of GetChannelManagers.
func (mr *MockChannelServiceMockRecorder) GetChannelManagers(ctx, telegramChannelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelManagers", reflect.TypeOf((*MockChannelService)(nil).GetChannelManagers), ctx, telegramChannelID)
}

// GetUserChannels mocks base method.
func (m *MockChannelService) GetUserChannels(ctx context.Context) ([]dto.ChannelWithRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChannels", ctx)
	ret0, _ := ret[0].([]dto.ChannelWithRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChannels indicates an expected call of GetUserChannels.
func (mr *MockChannelServiceMockRecorder) GetUserChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChannels", reflect.TypeOf((*MockChannelService)(nil).GetUserChannels), ctx)
}

// RemoveManager mocks base method.
func (m *MockChannelService) RemoveManager(ctx context.Context, telegramChannelID, telegramID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveManager", ctx, telegramChannelID, telegramID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveManager indicates an expected call of RemoveManager.
func (mr *MockChannelServiceMockRecorder) RemoveManager(ctx, telegramChannelID, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveManager", reflect.TypeOf((*MockChannelService)(nil).RemoveManager), ctx, telegramChannelID, telegramID)
}
