// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bpva/ad-marketplace/internal/http/app (interfaces: BotService)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=app . BotService
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBotService is a mock of BotService interface.
type MockBotService struct {
	ctrl     *gomock.Controller
	recorder *MockBotServiceMockRecorder
	isgomock struct{}
}

// MockBotServiceMockRecorder is the mock recorder for MockBotService.
type MockBotServiceMockRecorder struct {
	mock *MockBotService
}

// NewMockBotService creates a new mock instance.
func NewMockBotService(ctrl *gomock.Controller) *MockBotService {
	mock := &MockBotService{ctrl: ctrl}
	mock.recorder = &MockBotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotService) EXPECT() *MockBotServiceMockRecorder {
	return m.recorder
}

// ProcessUpdate mocks base method.
func (m *MockBotService) ProcessUpdate(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUpdate", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockBotServiceMockRecorder) ProcessUpdate(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockBotService)(nil).ProcessUpdate), data)
}

// Token mocks base method.
func (m *MockBotService) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockBotServiceMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockBotService)(nil).Token))
}
